### PR TITLE
Update to download 7.1.0

### PR DESCRIPTION
**Pull request by rejas**
Switched to the new promise based API of download, updated dependencies and node versions
Picking PR up from https://github.com/kevva/bin-wrapper/pull/57

### CODE REVIEW

**Comment by rinella** [comment]
nice!  i see where I was going wrong now.

**Comment by XhmikosR** [comment]
@sindresorhus: thanks! Can you cut a new release too?

**Comment by sindresorhus** [comment]
@XhmikosR https://github.com/kevva/bin-wrapper/pull/60#issuecomment-404142576 needs to be done first. // @realityking

**Comment by rejas** [comment]
@sindresorhus what has to be done there in #60 that isnt already donehere? download is updated and the code is adapted to its new promise api.

**Pull request merged**
